mybatis:
  type-aliases-package: com.bdth.bootDemo.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://192.168.88.110:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&noAccessToProcedureBodies=true
    username: sysystem
    password: bdth@2018
#    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  thymeleaf:
#    prefix: /templates/
#    suffix: .html
#    mode: HTML
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379


#配置外部访问文件（把上传的图片视频文件放到E盘下的fileUpload文件夹下）

imagesPath: file:/E:/Users

server:
  servlet:
    context-path: /views
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:application-log4j.yml